name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-lint-and-typecheck:
    name: Test, Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv sovvenv
          source sovvenv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Check code formatting with Ruff
        run: |
          source sovvenv/bin/activate
          ruff format --check .

      - name: Run linter with Ruff
        run: |
          source sovvenv/bin/activate
          ruff check .

      - name: Run type check with Pyright
        run: |
          source sovvenv/bin/activate
          pyright .

      - name: Run tests with pytest
        run: |
          source sovvenv/bin/activate
          pytest
